In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
from PIL import Image

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
from tensorflow.keras.models import model_from_json
from tensorflow.keras.optimizers import Adam

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score as accuracy

In [2]:
# def AlexNet(X_train, y_train, **kwargs):
    
#     model = Sequential([
#         Conv2D(filters=96, kernel_size=(11,11), strides=(4,4), activation='relu', input_shape=(384, 512, 3)), # L1
#         MaxPooling2D(pool_size=(3,3), strides=(2,2)), # L2
#         Conv2D(filters=256, kernel_size=(5,5), strides=(1,1), activation='relu'), # L3
#         MaxPooling2D(pool_size=(3,3), strides=(2,2)), # L4
#         Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), activation='relu'), # L5
#         Conv2D(filters=384, kernel_size=(3,3), strides=(1,1), activation='relu'), # L6
#         Conv2D(filters=256, kernel_size=(3,3), strides=(1,1), activation='relu'), # L7
#         MaxPooling2D(pool_size=(3,3), strides=(2,2)), # L8
#         Flatten(),
#         Dense(4096, activation='relu'), # L9
#         Dropout(0.5),
#         Dense(4096, activation='relu'), # L10
#         Dropout(0.5),
#         Dense(3, activation='softmax')
#     ])
    
#     model.compile(loss='categorical_crossentropy', optimizer=Adam(learning_rate=1e-5), metrics=['accuracy'])
#     history = model.fit(X_train, y_train, **kwargs)
#     return model, history

In [3]:
X = []
folder = 'processed_photos'
folder_list = os.listdir(folder)
for file in folder_list:
    img = Image.open(f'{folder}/{file}')
    arr = np.array(img)
    X.append(arr)

print()
print('# actual photos:', len(X))
X = np.array(X)
print('done')


# actual photos: 6
done


In [4]:
# from tensorflow.keras.models import model_from_json
model_name = 'AlexNet100'
with open(f'{model_name}.json') as jf:
    json = jf.read()
model = model_from_json(json)
model.load_weights(f'{model_name}.h5')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 94, 126, 96)       34944     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 46, 62, 96)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 42, 58, 256)       614656    
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 20, 28, 256)       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 18, 26, 384)       885120    
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 16, 24, 384)       1327488   
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 14, 22, 256)       8

In [5]:
y_pred = model.predict(X)
print(y_pred)

[[0.9911016  0.0074161  0.0014823 ]
 [0.67447895 0.11688446 0.20863658]
 [0.908372   0.02746939 0.06415857]
 [0.94328403 0.01817413 0.03854185]
 [0.33650467 0.10944327 0.5540521 ]
 [0.70845443 0.00745823 0.28408727]]
